# Generated by Django 2.0 on 2021-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('pic', models.ImageField(upload_to='menu/')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='pic',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
