# Generated by Django 2.0 on 2021-08-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210812_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
