# Generated by Django 2.0 on 2021-08-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210813_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=80)),
                ('event', models.CharField(max_length=80)),
                ('persons', models.CharField(max_length=80)),
                ('venue', models.CharField(max_length=80)),
                ('time', models.CharField(max_length=80)),
                ('date', models.CharField(max_length=80)),
                ('pic', models.ImageField(default='', upload_to='img/')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
