# Generated by Django 2.0 on 2021-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='pic',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='persons',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
